apiVersion: v1
kind: Service
metadata:
  name: rest-service-eureka
  labels:
    app: rest-service-eureka
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 8080
  selector:
    app: rest-service-eureka
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-service-eureka
  labels:
    app: rest-service-eureka
spec:
  selector:
    matchLabels:
      app: rest-service-eureka
  replicas: 1
  minReadySeconds: 15
  template:
    metadata:
      labels:
        app: rest-service-eureka
    spec:
      containers:
      - image: mdavireddy/rest-service-eureka:latest
        imagePullPolicy: Always
        name: rest-service-eureka
        ports:
          - containerPort: 8080