apiVersion: v1
kind: Service
metadata:
  name: rest-service-eureka
  labels:
    app: rest-service-eureka
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 8080
  selector:
    app: rest-service-eureka
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-service-eureka
  labels:
    app: rest-service-eureka
spec:
  selector:
    matchLabels:
      app: rest-service-eureka
  replicas: 1
  minReadySeconds: 15
  template:
    metadata:
      labels:
        app: rest-service-eureka
    spec:
      {{- if .Values.dockercfg}}  
      imagePullSecrets:  
      - name: {{.Values.name}}-dockercfg  
       {{- end}}  
      containers:
      - image: {{.Values.image}}  
        imagePullPolicy: Always
        name: rest-service
        ports:
          - containerPort: 8080
